// Auto-generated by OpenLane
module tinyjambu_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input ena,
  input[2:0] sel_type,
  input[127:0] key,
  input[95:0] nonce,
  input[127:0] ad,
  input[4:0] ad_length,
  input[4:0] data_length,
  input[127:0] data_in,
  input[63:0] tag_in,
  output valid,
  output[63:0] tag,
  output[127:0] data_out,
  output done
);
endmodule
